<?php
/**
 * @file
 * node_exp.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function node_exp_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Contact',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '4acb2d68-da8a-400f-9f0c-1596776ddfb6',
  'type' => 'page',
  'language' => 'und',
  'created' => 1415856035,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '12a6bc4c-6a90-4e93-a88c-905a962fa330',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2 class="block-title">Contact Info</h2>
<div class="iframe-wrapper">
<iframe frameborder="0" height="280" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d19889.743778619053!2d-0.060909985041733214!3d51.454154306745174!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487603c82a306821%3A0xa38eb1d301bf8621!2zTWFybW9yYSBSZCwgTG9uZG9uIFNFMjIgMFJYLCDQktC10LvQuNC60L7QsdGA0LjRgtCw0L3QuNGP!5e0!3m2!1sru!2sru!4v1414052995059" style="border:0" width="460"></iframe>
</div>
<div class="contact-column" id="left-contact">
  <strong>London</strong>
  <ul>
    <li>269 Main Street</li>
    <li>London England</li>
    <li>Call:+00-000-0000</li>
    <li>Email: contact@yourdomain.com</li>
  </ul>
</div>
<div class="contact-column" id="right-contact">
  <strong>New York</strong>
  <ul>
    <li>112/e Time Square</li>
    <li>NewYork USA</li>
    <li>Call: +00-000-0000</li>
    <li>Email: contact@yourdomain.com</li>
  </ul>
</div>

<h2>About Us</h2>

Abico amet autem diam imputo molior pagus pecus uxor. Brevitas cui eu ille iriure luptatum plaga.

Defui dolor hos imputo valde. Eros ex macto molior quidne refero uxor voco. Adipiscing genitus olim persto zelus. Comis defui dolus esse huic rusticus velit wisi. Aliquam capto elit gilvus incassum os ratis refoveo. Adipiscing appellatio importunus neo singularis usitas vel. Euismod exputo immitto interdico macto mauris quidne.

Eum ibidem ideo. Dolor iaceo jumentum macto probo vulputate. Et macto proprius tum zelus. Mauris sed suscipit tego utinam. Dolor hendrerit lucidus quidem veniam venio. Blandit dolor neque quae quia sino validus vero. Hendrerit in meus mos rusticus similis.

Acsi illum immitto jumentum. Ea exputo genitus importunus luptatum nimis nunc pecus validus wisi. Abdo antehabeo bene causa imputo melior neo paratus ullamcorper vicis. Consequat ea enim eros esse iriure mauris rusticus validus vel. Abigo jugis loquor sagaciter si tego velit vero. Blandit fere gravis ille imputo iustum persto tincidunt vindico wisi. Commoveo erat jumentum lobortis nibh nisl os sudo velit vicis.',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<h2 class="block-title">Contact Info</h2>
<div class="iframe-wrapper">
<iframe frameborder="0" height="280" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d19889.743778619053!2d-0.060909985041733214!3d51.454154306745174!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487603c82a306821%3A0xa38eb1d301bf8621!2zTWFybW9yYSBSZCwgTG9uZG9uIFNFMjIgMFJYLCDQktC10LvQuNC60L7QsdGA0LjRgtCw0L3QuNGP!5e0!3m2!1sru!2sru!4v1414052995059" style="border:0" width="460"></iframe></div>
<div class="contact-column" id="left-contact">
  <strong>London</strong>
<ul><li>269 Main Street</li>
<li>London England</li>
<li>Call:+00-000-0000</li>
<li>Email: <a href="mailto:contact@yourdomain.com">contact@yourdomain.com</a></li>
</ul></div>
<div class="contact-column" id="right-contact">
  <strong>New York</strong>
<ul><li>112/e Time Square</li>
<li>NewYork USA</li>
<li>Call: +00-000-0000</li>
<li>Email: <a href="mailto:contact@yourdomain.com">contact@yourdomain.com</a></li>
</ul></div>
<h2>About Us</h2>
<p>Abico amet autem diam imputo molior pagus pecus uxor. Brevitas cui eu ille iriure luptatum plaga.</p>
<p>Defui dolor hos imputo valde. Eros ex macto molior quidne refero uxor voco. Adipiscing genitus olim persto zelus. Comis defui dolus esse huic rusticus velit wisi. Aliquam capto elit gilvus incassum os ratis refoveo. Adipiscing appellatio importunus neo singularis usitas vel. Euismod exputo immitto interdico macto mauris quidne.</p>
<p>Eum ibidem ideo. Dolor iaceo jumentum macto probo vulputate. Et macto proprius tum zelus. Mauris sed suscipit tego utinam. Dolor hendrerit lucidus quidem veniam venio. Blandit dolor neque quae quia sino validus vero. Hendrerit in meus mos rusticus similis.</p>
<p>Acsi illum immitto jumentum. Ea exputo genitus importunus luptatum nimis nunc pecus validus wisi. Abdo antehabeo bene causa imputo melior neo paratus ullamcorper vicis. Consequat ea enim eros esse iriure mauris rusticus validus vel. Abigo jugis loquor sagaciter si tego velit vero. Blandit fere gravis ille imputo iustum persto tincidunt vindico wisi. Commoveo erat jumentum lobortis nibh nisl os sudo velit vicis.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-11-13 05:20:35 +0000',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Features',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8de3e989-304f-4123-851d-858016392048',
  'type' => 'page',
  'language' => 'und',
  'created' => 1415854603,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '812c9f99-c0d0-46ca-8a93-6b3cc425dc9c',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Abico amet autem diam imputo molior pagus pecus uxor. Brevitas cui eu ille iriure luptatum plaga.

Defui dolor hos imputo valde. Eros ex macto molior quidne refero uxor voco. Adipiscing genitus olim persto zelus. Comis defui dolus esse huic rusticus velit wisi. Aliquam capto elit gilvus incassum os ratis refoveo. Adipiscing appellatio importunus neo singularis usitas vel. Euismod exputo immitto interdico macto mauris quidne.

Eum ibidem ideo. Dolor iaceo jumentum macto probo vulputate. Et macto proprius tum zelus. Mauris sed suscipit tego utinam. Dolor hendrerit lucidus quidem veniam venio. Blandit dolor neque quae quia sino validus vero. Hendrerit in meus mos rusticus similis.

Abico amet autem diam imputo molior pagus pecus uxor. Brevitas cui eu ille iriure luptatum plaga.

Defui dolor hos imputo valde. Eros ex macto molior quidne refero uxor voco. Adipiscing genitus olim persto zelus. Comis defui dolus esse huic rusticus velit wisi. Aliquam capto elit gilvus incassum os ratis refoveo. Adipiscing appellatio importunus neo singularis usitas vel. Euismod exputo immitto interdico macto mauris quidne.

Eum ibidem ideo. Dolor iaceo jumentum macto probo vulputate. Et macto proprius tum zelus. Mauris sed suscipit tego utinam. Dolor hendrerit lucidus quidem veniam venio. Blandit dolor neque quae quia sino validus vero. Hendrerit in meus mos rusticus similis.

Abico amet autem diam imputo molior pagus pecus uxor. Brevitas cui eu ille iriure luptatum plaga.

Defui dolor hos imputo valde. Eros ex macto molior quidne refero uxor voco. Adipiscing genitus olim persto zelus. Comis defui dolus esse huic rusticus velit wisi. Aliquam capto elit gilvus incassum os ratis refoveo. Adipiscing appellatio importunus neo singularis usitas vel. Euismod exputo immitto interdico macto mauris quidne.

Eum ibidem ideo. Dolor iaceo jumentum macto probo vulputate. Et macto proprius tum zelus. Mauris sed suscipit tego utinam. Dolor hendrerit lucidus quidem veniam venio. Blandit dolor neque quae quia sino validus vero. Hendrerit in meus mos rusticus similis.

Abico amet autem diam imputo molior pagus pecus uxor. Brevitas cui eu ille iriure luptatum plaga.

Defui dolor hos imputo valde. Eros ex macto molior quidne refero uxor voco. Adipiscing genitus olim persto zelus. Comis defui dolus esse huic rusticus velit wisi. Aliquam capto elit gilvus incassum os ratis refoveo. Adipiscing appellatio importunus neo singularis usitas vel. Euismod exputo immitto interdico macto mauris quidne.

Eum ibidem ideo. Dolor iaceo jumentum macto probo vulputate. Et macto proprius tum zelus. Mauris sed suscipit tego utinam. Dolor hendrerit lucidus quidem veniam venio. Blandit dolor neque quae quia sino validus vero. Hendrerit in meus mos rusticus similis.

',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Abico amet autem diam imputo molior pagus pecus uxor. Brevitas cui eu ille iriure luptatum plaga.</p>
<p>Defui dolor hos imputo valde. Eros ex macto molior quidne refero uxor voco. Adipiscing genitus olim persto zelus. Comis defui dolus esse huic rusticus velit wisi. Aliquam capto elit gilvus incassum os ratis refoveo. Adipiscing appellatio importunus neo singularis usitas vel. Euismod exputo immitto interdico macto mauris quidne.</p>
<p>Eum ibidem ideo. Dolor iaceo jumentum macto probo vulputate. Et macto proprius tum zelus. Mauris sed suscipit tego utinam. Dolor hendrerit lucidus quidem veniam venio. Blandit dolor neque quae quia sino validus vero. Hendrerit in meus mos rusticus similis.</p>
<p>Abico amet autem diam imputo molior pagus pecus uxor. Brevitas cui eu ille iriure luptatum plaga.</p>
<p>Defui dolor hos imputo valde. Eros ex macto molior quidne refero uxor voco. Adipiscing genitus olim persto zelus. Comis defui dolus esse huic rusticus velit wisi. Aliquam capto elit gilvus incassum os ratis refoveo. Adipiscing appellatio importunus neo singularis usitas vel. Euismod exputo immitto interdico macto mauris quidne.</p>
<p>Eum ibidem ideo. Dolor iaceo jumentum macto probo vulputate. Et macto proprius tum zelus. Mauris sed suscipit tego utinam. Dolor hendrerit lucidus quidem veniam venio. Blandit dolor neque quae quia sino validus vero. Hendrerit in meus mos rusticus similis.</p>
<p>Abico amet autem diam imputo molior pagus pecus uxor. Brevitas cui eu ille iriure luptatum plaga.</p>
<p>Defui dolor hos imputo valde. Eros ex macto molior quidne refero uxor voco. Adipiscing genitus olim persto zelus. Comis defui dolus esse huic rusticus velit wisi. Aliquam capto elit gilvus incassum os ratis refoveo. Adipiscing appellatio importunus neo singularis usitas vel. Euismod exputo immitto interdico macto mauris quidne.</p>
<p>Eum ibidem ideo. Dolor iaceo jumentum macto probo vulputate. Et macto proprius tum zelus. Mauris sed suscipit tego utinam. Dolor hendrerit lucidus quidem veniam venio. Blandit dolor neque quae quia sino validus vero. Hendrerit in meus mos rusticus similis.</p>
<p>Abico amet autem diam imputo molior pagus pecus uxor. Brevitas cui eu ille iriure luptatum plaga.</p>
<p>Defui dolor hos imputo valde. Eros ex macto molior quidne refero uxor voco. Adipiscing genitus olim persto zelus. Comis defui dolus esse huic rusticus velit wisi. Aliquam capto elit gilvus incassum os ratis refoveo. Adipiscing appellatio importunus neo singularis usitas vel. Euismod exputo immitto interdico macto mauris quidne.</p>
<p>Eum ibidem ideo. Dolor iaceo jumentum macto probo vulputate. Et macto proprius tum zelus. Mauris sed suscipit tego utinam. Dolor hendrerit lucidus quidem veniam venio. Blandit dolor neque quae quia sino validus vero. Hendrerit in meus mos rusticus similis.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2014-11-13 04:56:43 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Contact Form',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '5c2af920-833c-4332-8d83-7e59e5afab35',
  'type' => 'webform',
  'language' => 'und',
  'created' => 1415690098,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'c9413d93-9856-40e1-8f13-9c0c94703ef8',
  'revision_uid' => 1,
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => 131,
    'next_serial' => 1,
    'confirmation' => '',
    'confirmation_format' => 'filtered_html',
    'redirect_url' => '<confirmation>',
    'status' => 1,
    'block' => 1,
    'allow_draft' => 0,
    'auto_save' => 0,
    'submit_notice' => 1,
    'submit_text' => '',
    'submit_limit' => -1,
    'submit_interval' => -1,
    'total_submit_limit' => -1,
    'total_submit_interval' => -1,
    'progressbar_bar' => 1,
    'progressbar_page_number' => 0,
    'progressbar_percent' => 0,
    'progressbar_pagebreak_labels' => 1,
    'progressbar_include_confirmation' => 1,
    'progressbar_label_first' => 'Start',
    'progressbar_label_confirmation' => 'Complete',
    'preview' => 0,
    'preview_next_button_label' => '',
    'preview_prev_button_label' => '',
    'preview_title' => '',
    'preview_message' => '',
    'preview_message_format' => 'filtered_html',
    'preview_excluded_components' => array(),
    'record_exists' => TRUE,
    'roles' => array(
      0 => 1,
      1 => 2,
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 131,
        'cid' => 1,
        'pid' => 0,
        'form_key' => 'name',
        'name' => 'Name',
        'type' => 'textfield',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'wrapper_classes' => '',
          'css_classes' => '',
          'width' => 220,
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'disabled' => 0,
          'unique' => 0,
          'description' => '',
          'placeholder' => '',
          'attributes' => array(),
          'analysis' => FALSE,
        ),
        'required' => 0,
        'weight' => 0,
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 131,
        'cid' => 2,
        'pid' => 0,
        'form_key' => 'e_mail',
        'name' => 'E-mail',
        'type' => 'textfield',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'wrapper_classes' => '',
          'css_classes' => '',
          'width' => 220,
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'disabled' => 0,
          'unique' => 0,
          'description' => '',
          'placeholder' => '',
          'attributes' => array(),
          'analysis' => FALSE,
        ),
        'required' => 0,
        'weight' => 1,
        'page_num' => 1,
      ),
      3 => array(
        'nid' => 131,
        'cid' => 3,
        'pid' => 0,
        'form_key' => 'subject',
        'name' => 'Subject',
        'type' => 'textfield',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'wrapper_classes' => '',
          'css_classes' => '',
          'width' => 460,
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'disabled' => 0,
          'unique' => 0,
          'description' => '',
          'placeholder' => '',
          'attributes' => array(),
          'analysis' => FALSE,
        ),
        'required' => 0,
        'weight' => 2,
        'page_num' => 1,
      ),
      4 => array(
        'nid' => 131,
        'cid' => 4,
        'pid' => 0,
        'form_key' => 'message',
        'name' => 'Message',
        'type' => 'textarea',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'wrapper_classes' => '',
          'css_classes' => '',
          'resizable' => 0,
          'cols' => '',
          'rows' => '',
          'disabled' => 0,
          'description' => '',
          'placeholder' => '',
          'attributes' => array(),
          'analysis' => FALSE,
        ),
        'required' => 0,
        'weight' => 3,
        'page_num' => 1,
      ),
    ),
    'conditionals' => array(),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2014-11-11 07:14:58 +0000',
);
  return $nodes;
}
