<?php
/**
 * @file
 * Code for the content feature.
 */

include_once 'content.features.inc';

/**
 * Implements hook_init().
 */
function content_init() {
  $flag = variable_get('custom_flag_for_corporate_theme');
  if (!empty($flag)) {
    if ($flag == 'off') {
      db_update('system')
        ->fields(array('status' => 1))
        ->condition('type', 'theme')
        ->condition('name', 'corporate_theme')
        ->execute();
      variable_del('custom_flag_for_corporate_theme');
    }
  }
}